name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: jar cvf demo.war .
      
    - name: Deploy
      run: curl -T "demo.war" "http://admin:123456@http://7725a065.ngrok.io/manager/text/deploy?path=/myapp&update=true"
