name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    - name: war file build
      run: jar cvf spiderhost.war .
      
    - name: List files
      run: ls
      
    - name: Deploy
      run: curl -T "spiderhost.war" "http://admin:123456@07ffef3b.ngrok.io/manager/text/deploy?path=/spiderhost&update=true"
